version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
    # (this is just an example, not intended to be a production configuration)
